package com.stevekung.modernmobspawn;

import java.util.Collections;

import com.stevekung.modernmobspawn.core.Tags;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Tags.MOD_ID, name = Tags.MOD_NAME, version = Tags.VERSION, dependencies = ModernMobSpawn.MAIN_DEPENDENCIES)
public class ModernMobSpawn
{
    public static final String URL = "https://www.curseforge.com/minecraft/mc-mods/modern-mob-spawn";
    protected static final String MAIN_DEPENDENCIES = "required-after:mixinbooter@[" + Tags.MIXIN_BOOTER_VERSION + ",); ";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        initModInfo(event.getModMetadata());
    }

    private static void initModInfo(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = Tags.MOD_ID;
        info.name = Tags.MOD_NAME;
        info.version = Tags.VERSION;
        info.description = "A tiny mod that brings modern mob spawn condition into 1.12.2";
        info.url = URL;
        info.authorList = Collections.singletonList("SteveKunG");
    }
}